"""add_auth_user_sync_trigger

Revision ID: 6261b6a223ed
Revises: 2d7f40a704ec
Create Date: 2025-12-08 08:57:03.692845+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6261b6a223ed'
down_revision: Union[str, None] = '2d7f40a704ec'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        CREATE OR REPLACE FUNCTION public.handle_new_user()
            RETURNS TRIGGER AS $$
        BEGIN
            INSERT INTO public.users (id, email, full_name, is_active, is_superuser, password_hash)
            VALUES (
                NEW.id,
                NEW.email,
                NEW.raw_user_meta_data->>'full_name',
                true,
                false,
                NULL
            );
            RETURN NEW;
        END;
        $$ LANGUAGE plpgsql SECURITY DEFINER;
    """)

    op.execute("""
        DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
        CREATE TRIGGER on_auth_user_created
            AFTER INSERT ON auth.users
            FOR EACH ROW EXECUTE FUNCTION public.handle_new_user();
    """)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.execute("""
        DROP TRIGGER IF EXISTS on_auth_user_created ON auth.users;
    """)
    op.execute("""
        DROP FUNCTION IF EXISTS public.handle_new_user();
    """)
    # ### end Alembic commands ###