"""fix_user_usage_fk

Revision ID: 2d7f40a704ec
Revises: a7b145a7dfbe
Create Date: 2025-12-04 08:21:12.762401+00:00

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d7f40a704ec'
down_revision: Union[str, None] = 'a7b145a7dfbe'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('user_usage',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('user_id', sa.UUID(), nullable=False),
    sa.Column('daily_cost', sa.Float(), nullable=False),
    sa.Column('daily_requests', sa.Float(), nullable=False),
    sa.Column('daily_reset_date', sa.DateTime(), nullable=False),
    sa.Column('monthly_cost', sa.Float(), nullable=False),
    sa.Column('monthly_requests', sa.Float(), nullable=False),
    sa.Column('monthly_reset_date', sa.DateTime(), nullable=False),
    sa.Column('daily_budget_exceeded', sa.Boolean(), nullable=False),
    sa.Column('monthly_budget_exceeded', sa.Boolean(), nullable=False),
    sa.Column('updated_at', sa.DateTime(), nullable=False),
    sa.ForeignKeyConstraint(['user_id'], ['users.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_user_usage_user_id'), 'user_usage', ['user_id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_user_usage_user_id'), table_name='user_usage')
    op.drop_table('user_usage')
    # ### end Alembic commands ###